### ISSUE TITLE
Front-end setup

### ISSUE THREAD

**Issue by lthai423** [TheWalkingDrunk/theWalkingDrunk#1]
Install React.js, Babel, Webpack, etc.
Components must render correctly.
States must be able to be stored.
Folder organization must be extensible and as organized as possible.

**Comment by lthai423** [comment]
How is it going Surender? Try posting your plan as a comment on here so we can help you review it.  Click "Preview" for a quick proofread and then post it.  We can all take turns helping you revise your plan.

**Comment by surenderbhagtana** [comment]
1) Bar/Club tab :- render by Yelp API
2) current destination :- either current or specific destination according to customer's choice
3) final destination :- tab 2 and 3 will be render by Google map
4) GO tab:- everything will work while we hit the GO tab.

result should give us all the bar or clubs on the map to our final destination.
then if we want to pick any of the specific bar then google map should render the customer from the current place to that bar's address.

**Comment by surenderbhagtana** [comment]
I added a visual front page on slack

**Comment by lthai423** [comment]
Cool beans Surender.

Here is also a link to help you set up the configuration files:
https://www.codementor.io/reactjs/tutorial/beginner-guide-setup-reactjs-environment-npm-babel-6-webpack

I have also assigned myself to this task to help you out.

**Comment by lthai423** [comment]
I'm gonna say that those components that you outlined seem to fall in later sprints.  I've left documentation with my branches, commits, and merges for this task.  Check em' out and let me know if you need anything else. 

[CLOSED]

**Comment by bhagtana** [comment]
should I make folders for client like that tutorial you sent me for setup react, babel, and webpack?

**Comment by surenderbhagtana** [comment]
okay I am looking into it.
